
  export const mode1_Sliders = [
    {
      "id":0,
      "min":0,
      "max":2,
      "step":0.1,
      "value":1
    },
    {
      "id":1,
      "min":0,
      "max":2,
      "step":0.1,
      "value":1
    },
    {
      "id":2,
      "min":0,
      "max":2,
      "step":0.1,
      "value":1
    },
    {
        "id":3,
        "min":0,
        "max":2,
        "step":0.1,
        "value":1
      },
      {
        "id":4,
        "min":0,
        "max":2,
        "step":0.1,
        "value":1
      },
      {
        "id":5,
        "min":0,
        "max":2,
        "step":0.1,
        "value":1
      },
      {
        "id":6,
        "min":0,
        "max":2,
        "step":0.1,
        "value":1
      },
      {
        "id":7,
        "min":0,
        "max":2,
        "step":0.1,
        "value":1
      },
      {
        "id":8,
        "min":0,
        "max":2,
        "step":0.1,
        "value":1
      },
      {
        "id":9,
        "min":0,
        "max":2,
        "step":0.1,
        "value":1
      }
  ]

  export const mode2_Sliders = [
    {
      "id":0,
      "min":0,
      "max":500,
      "step":1,
      "value":250,
      "label":"piano"
    },
    {
      "id":1,
      "min":0,
      "max":500,
      "step":1,
      "value":250,
      "label":"guitar"
    },
    {
        "id":2,
        "min":0,
        "max":500,
        "step":1,
        "value":250,
        "label":"drums"
      }
  ]

export const mode3_sliders = [
    {
        "id":0,
        "min":0,
        "max":500,
        "step":1,
        "value":250,
        "label":"A"
        
      },
      {
        "id":1,
        "min":0,
        "max":500,
        "step":1,
        "value":250,
        "label":"B"
      },
      {
        "id":2,
        "min":0,
        "max":500,
        "step":1,
        "value":250,
        "label":"C"
      },
      {
        "id":3,
        "min":0,
        "max":500,
        "step":1,
        "value":250,
        "label":"D"
      }
]